### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by smexyy** [Gedsh/InviZible#292]
```
type: crash
package: pan.alexander.tordnscrypt.stable:3232
process: pan.alexander.tordnscrypt.stable
processUptime: 41893 + 51 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2032496 bytes
Bundle stats:
  androidx.lifecycle.BundlableSavedStateRegistry.key [size=2031168]
    android:support:activity-result [size=1176]
    android:support:fragments [size=2029680]
      android:support:fragments [size=2029608]
PersistableBundle stats:
  [null]
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:146)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:894)
Caused by: android.os.TransactionTooLargeException: data parcel size 2032496 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:586)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1527)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:101)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:135)
	... 8 more
``

**Comment by Gedsh** [comment]
These logs do not contain information about the source of the crash. I need detailed logs from InviZible and an explanation of when it happened and how to reproduce it. Otherwise I will not be able to fix it.

**Comment by smexyy** [comment]
> These logs do not contain information about the source of the crash. I need detailed logs from InviZible and an explanation of when it happened and how to reproduce it. Otherwise I will not be able to fix it.

Please, check below link for screen record. In nutshell, the app crash when trying open link from blocklist via browser.
https://streamable.com/fo4q97

**Comment by Gedsh** [comment]
Thank you! Good catch. I have found the source of the crash.

**Comment by Gedsh** [comment]
This is fixed via https://github.com/Gedsh/InviZible/commit/f475d8a497dc00722b5f899fc76be93856e1a495
