### ISSUE TITLE
[crash] RejectedExecutionException on Beta v0.3.1

### ISSUE THREAD

**Issue by runo280** [Gedsh/InviZible#4]
When I clicked over "I2P Setting"
```
2019-11-07 21:40:45.480 17970-17970/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: pan.alexander.tordnscrypt, PID: 17970
    java.lang.RuntimeException: Unable to start activity ComponentInfo{pan.alexander.tordnscrypt/pan.alexander.tordnscrypt.SettingsActivity}: java.util.concurrent.RejectedExecutionException: Task e.a.a.j.v.a$d@3d74985 rejected from java.util.concurrent.ThreadPoolExecutor@cef03da[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 12]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.util.concurrent.RejectedExecutionException: Task e.a.a.j.v.a$d@3d74985 rejected from java.util.concurrent.ThreadPoolExecutor@cef03da[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 12]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2085)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
        at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:624)
        at e.a.a.j.v.a.b(Unknown Source:7)
        at pan.alexander.tordnscrypt.SettingsActivity.onCreate(:20)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by Gedsh** [comment]
This means that one of the services was terminated when the app is active. But it is not clear how you reach this state. Can you attach log from Invisible: Menu -> Logs -> Save Logs after crash?

**Comment by runo280** [comment]
Here you are: [InvizibleLogs.txt](https://github.com/Gedsh/InviZible/files/3823204/InvizibleLogs.txt)

**Comment by Gedsh** [comment]
Thank you But there is nothing to look. I need the log right after the crash. It shows that everything is fine now.
